info:
  java:
    enabled: true
server:
  port: 8090
course:
  message: Hello World
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles:
    active: prod
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

